import { prisma } from "./config/prisma.js";

const seedDB = async () => {
  try {
    await prisma.product.deleteMany({});
    console.log("Cleared existing products");

    const products: any = [
      {
        name: "Butter Croissant 100g",
        description: "Flaky and buttery",
        price: 45,
        originalPrice: 50,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/zvoeqbvrbrt7atqj0dbu.png",
        category: "bakery",
        unit: "100g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Organic Quinoa 500g",
        description: "High protein, Gluten-free",
        price: 420,
        originalPrice: 450,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cxrrgnf12xuhkr4dyhi2.png",
        category: "pantry-staples",
        unit: "500g",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Brown Bread 400g",
        description: "Soft and healthy, Ideal for breakfast",
        price: 35,
        originalPrice: 40,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vy1xa7zovcu22smzapzv.png",
        category: "bakery",
        unit: "400g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Barley 1kg",
        description: "Rich in fiber, Helps digestion",
        price: 140,
        originalPrice: 150,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/spb5sgy8g24rned9nwog.png",
        category: "pantry-staples",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Knorr Cup Soup 70g",
        description: "Convenient and tasty",
        price: 30,
        originalPrice: 35,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vnzb2qbwtpab5gnqvx0f.png",
        category: "pantry-staples",
        unit: "70g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Maggi Noodles 280g",
        description: "Instant and easy to cook",
        price: 50,
        originalPrice: 55,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dsep7owmwvfrukzbslqo.png",
        category: "pantry-staples",
        unit: "280g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Sprite 1.5L",
        description: "Chilled and refreshing, Perfect for celebrations",
        price: 60,
        originalPrice: 75,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/daiglpvgna1dlhjplbve.png",
        category: "beverages",
        unit: "1.5L",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Carrot 500g",
        description:
          "Sweet and crunchy, Good for eyesight, Ideal for juices and salads",
        price: 44,
        originalPrice: 50,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ceqgisupuizyste9aifg.png",
        category: "fruits-vegetables",
        unit: "500g",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Coca-Cola 1.5L",
        description: "Perfect for parties and gatherings, Best served chilled",
        price: 75,
        originalPrice: 80,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/eljxcdud6fduwfim5rdx.png",
        category: "beverages",
        unit: "1.5L",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Brown Rice 1kg",
        description: "Whole grain and nutritious",
        price: 110,
        originalPrice: 120,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dboutcrkdjhoxcvbbqne.png",
        category: "pantry-staples",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Eggs 12 pcs",
        description:
          "Farm fresh, Rich in protein, Ideal for breakfast and baking",
        price: 85,
        originalPrice: 90,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cnjrpbcnqesqxy1wr30g.png",
        category: "dairy-eggs",
        unit: "12pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Banana 1 kg",
        description:
          "Sweet and ripe, High in potassium, Great for smoothies and snacking",
        price: 45,
        originalPrice: 50,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dsnmko6gqtyw31okby80.png",
        category: "fruits-vegetables",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Basmati Rice 5kg",
        description: "Long grain and aromatic, Perfect for biryani",
        price: 520,
        originalPrice: 550,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/evuovl2nlwdjukosfz23.png",
        category: "pantry-staples",
        unit: "5kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Onion 500g",
        description: "Fresh and pungent, Perfect for cooking, A kitchen staple",
        price: 45,
        originalPrice: 50,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/wnvtwlm2tphqburhsmyc.png",
        category: "fruits-vegetables",
        unit: "500g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "7 Up 1.5L",
        description: "Refreshing lemon-lime flavor",
        price: 70,
        originalPrice: 76,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/qt1ypzsoqni12ghf2ryp.png",
        category: "beverages",
        unit: "1.5L",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Spinach 500g",
        description:
          "Rich in iron, High in vitamins, Perfect for soups and salads",
        price: 15,
        originalPrice: 18,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/bhrtl76sscvmeiq4kchm.png",
        category: "fruits-vegetables",
        unit: "500g",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Orange 1 kg",
        description:
          "Juicy and sweet, Rich in Vitamin C, Perfect for juices and salads",
        price: 75,
        originalPrice: 80,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/r1wxfortw5h12g7egx7k.png",
        category: "fruits-vegetables",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Wheat Flour 5kg",
        description: "Soft and fluffy rotis, Rich in nutrients",
        price: 230,
        originalPrice: 250,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooitbkcjcky0gkjmkatb.png",
        category: "pantry-staples",
        unit: "5kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Grapes 500g",
        description:
          "Fresh and juicy, Rich in antioxidants, Perfect for snacking and fruit salads",
        price: 65,
        originalPrice: 70,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/jsmb7caaokhnyci2coga.png",
        category: "fruits-vegetables",
        unit: "500g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Fanta 1.5L",
        description: "Sweet and fizzy",
        price: 65,
        originalPrice: 70,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/nexecd3mgyzrpeun1bee.png",
        category: "beverages",
        unit: "1.5L",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Paneer 200g",
        description:
          "Soft and fresh, Rich in protein, Ideal for curries and snacks",
        price: 85,
        originalPrice: 90,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vihqr6wquv57byurvz46.png",
        category: "dairy-eggs",
        unit: "200g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Mango 1 kg",
        description:
          "Sweet and flavorful, Perfect for smoothies and desserts, Rich in Vitamin A",
        price: 140,
        originalPrice: 150,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/nb1mpxuo4fdcik6ey5yj.png",
        category: "fruits-vegetables",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Tomato 1 kg",
        description:
          "Juicy and ripe, Rich in Vitamin C, Perfect for salads and sauces, Farm fresh quality",
        price: 28,
        originalPrice: 30,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/kdbfytxisrjymgy0ubhk.png",
        category: "fruits-vegetables",
        unit: "1kg",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Potato 500g",
        description:
          "Fresh and organic, Rich in carbohydrates, Ideal for curries and fries",
        price: 35,
        originalPrice: 40,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tzibj2ntsnbn4e0u5kwv.png",
        category: "fruits-vegetables",
        unit: "500g",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Cheese 200g",
        description:
          "Creamy and delicious, Perfect for pizzas and sandwiches, Rich in calcium",
        price: 130,
        originalPrice: 140,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/gek3mmiig3lixlkpxks8.png",
        category: "dairy-eggs",
        unit: "200g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Amul Milk 1L",
        description: "Fresh milk, Rich in calcium",
        price: 55,
        originalPrice: 60,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooamzy497lhsj2gjuwby.png",
        category: "dairy-eggs",
        unit: "1L",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: "Apple 1 kg",
        description: "Boosts immunity, Rich in fiber",
        price: 90,
        originalPrice: 100,
        image:
          "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pjt1y6xdo46tluemhf0o.png",
        category: "fruits-vegetables",
        unit: "1kg",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },

      // ==================== PERSONAL CARE ====================
      {
        name: "Dettol Hand Wash 500ml",
        description: "Kills 99.9% of germs, gentle on skin",
        price: 120,
        originalPrice: 140,
        image: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "500ml",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 45,
      },
      {
        name: "Colgate MaxFresh 150g",
        description: "Cool mint flavor, Fights germs, Fresh breath",
        price: 85,
        originalPrice: 95,
        image: "https://images.unsplash.com/photo-1559304705-d4245c072e3e?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "150g",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 38,
      },
      {
        name: "Dove Shampoo 400ml",
        description: "Nourishing care, Silky smooth hair, For all hair types",
        price: 210,
        originalPrice: 240,
        image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "400ml",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 52,
      },
      {
        name: "Nivea Body Lotion 400ml",
        description: "Deep moisture care, 48hr hydration, Smooth skin",
        price: 295,
        originalPrice: 320,
        image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "400ml",
        stock: 100,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 63,
      },
      {
        name: "Lux Beauty Soap 4x75g",
        description: "Rich floral fragrance, Gentle on skin, For a luxurious feel",
        price: 150,
        originalPrice: 170,
        image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "4x75g",
        stock: 100,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 29,
      },
      {
        name: "Head & Shoulders 180ml",
        description: "Anti-dandruff shampoo, Menthol fresh, 100% flake-free",
        price: 180,
        originalPrice: 200,
        image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "180ml",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 41,
      },
      {
        name: "Patanjali Aloe Vera Gel 200ml",
        description: "Pure aloe vera, Multi-purpose skin care, Natural and organic",
        price: 95,
        originalPrice: 110,
        image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "200ml",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 55,
      },
      {
        name: "Listerine Mouthwash 250ml",
        description: "Antibacterial, Kills germs, Fresh mint flavor",
        price: 165,
        originalPrice: 185,
        image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "250ml",
        stock: 100,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 33,
      },
      {
        name: "Gillette Razor Blade 5pcs",
        description: "Precision cut, Smooth shave, Long-lasting blades",
        price: 320,
        originalPrice: 360,
        image: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "5pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 47,
      },
      {
        name: "Vaseline Petroleum Jelly 100ml",
        description: "Pure petroleum jelly, Multi-purpose moisturizer, Heals dry skin",
        price: 75,
        originalPrice: 85,
        image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
        category: "personal-care",
        unit: "100ml",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 60,
      },

      // ==================== SNACKS ====================
      {
        name: "Lays Classic Salted 95g",
        description: "Crispy and delicious, Classic salted flavor, Perfect for snacking",
        price: 20,
        originalPrice: 25,
        image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "95g",
        stock: 100,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 72,
      },
      {
        name: "Kurkure Masala Munch 90g",
        description: "Crunchy corn puffs, Tangy masala flavor",
        price: 20,
        originalPrice: 25,
        image: "https://images.unsplash.com/photo-1621447504864-d8686e1a468e?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "90g",
        stock: 100,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 55,
      },
      {
        name: "Haldiram Aloo Bhujia 200g",
        description: "Crispy spicy potato snack, Authentic Indian taste",
        price: 65,
        originalPrice: 75,
        image: "https://images.unsplash.com/photo-1609183480237-ccf9837091e1?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "200g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 48,
      },
      {
        name: "Cadbury Dairy Milk 120g",
        description: "Silky smooth milk chocolate, Pure joy in every bite",
        price: 80,
        originalPrice: 90,
        image: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "120g",
        stock: 100,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 85,
      },
      {
        name: "Monaco Biscuit 200g",
        description: "Light and crispy, Perfect tea-time snack",
        price: 30,
        originalPrice: 35,
        image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "200g",
        stock: 100,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 36,
      },
      {
        name: "Too Yumm Multigrain Chips 60g",
        description: "Baked not fried, Loaded with super grains, Guilt-free snacking",
        price: 35,
        originalPrice: 40,
        image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "60g",
        stock: 100,
        isOrganic: true,
        rating: 4.4,
        reviewCount: 28,
      },
      {
        name: "RC Kolae Peanut 200g",
        description: "Roasted and salted peanuts, High protein snack",
        price: 40,
        originalPrice: 50,
        image: "https://images.unsplash.com/photo-1567832020480-74ad3e14e585?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "200g",
        stock: 100,
        isOrganic: false,
        rating: 4.1,
        reviewCount: 22,
      },
      {
        name: "Oreo Biscuit 300g",
        description: "Cream filled chocolate sandwich cookies, Classic taste",
        price: 45,
        originalPrice: 50,
        image: "https://images.unsplash.com/photo-1579721307400-e35f38544b3f?w=400&h=400&fit=crop",
        category: "snacks",
        unit: "300g",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 67,
      },

      // ==================== FROZEN FOODS ====================
      {
        name: "Sugarcane Chicken Nuggets 400g",
        description: "Crispy on outside, juicy inside, Ready to fry or bake",
        price: 195,
        originalPrice: 220,
        image: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "400g",
        stock: 100,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 31,
      },
      {
        name: "Frozen Green Peas 500g",
        description: "Freshly frozen, Rich in protein and fiber, Retains nutrients",
        price: 65,
        originalPrice: 75,
        image: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "500g",
        stock: 100,
        isOrganic: true,
        rating: 4.4,
        reviewCount: 42,
      },
      {
        name: "Amul Vanilla Ice Cream 500ml",
        description: "Creamy vanilla flavor, Rich and smooth, Perfect dessert",
        price: 110,
        originalPrice: 130,
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "500ml",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 58,
      },
      {
        name: "McCain Smiles 425g",
        description: "Crispy potato smiles, Fun and tasty, Kids love them",
        price: 135,
        originalPrice: 150,
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "425g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 44,
      },
      {
        name: "Frozen Mixed Vegetables 1kg",
        description: "Carrots, peas, beans, corn - ready to cook, Farm fresh quality",
        price: 85,
        originalPrice: 95,
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "1kg",
        stock: 100,
        isOrganic: true,
        rating: 4.3,
        reviewCount: 35,
      },
      {
        name: "Kwality Walls Cornetto 4pcs",
        description: "Chocolate cone ice cream, Crispy wafer, Choco chips topping",
        price: 140,
        originalPrice: 160,
        image: "https://images.unsplash.com/photo-1570197571499-166b36435e9f?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "4pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 61,
      },
      {
        name: "Frozen Paratha 8pcs",
        description: "Ready-to-cook layered flatbread, Soft and flaky, Heat and serve",
        price: 90,
        originalPrice: 105,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=400&fit=crop",
        category: "frozen-foods",
        unit: "8pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 27,
      },

      // ==================== MEAT & SEAFOOD ====================
      {
        name: "Chicken Breast Boneless 500g",
        description: "Fresh and tender, High protein, Perfect for grilling and curries",
        price: 220,
        originalPrice: 250,
        image: "https://images.unsplash.com/photo-1604503468506-a8da13d82571?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "500g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 53,
      },
      {
        name: "Fresh Salmon Fillet 300g",
        description: "Rich in omega-3, Premium quality, Great for grilling",
        price: 450,
        originalPrice: 500,
        image: "https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "300g",
        stock: 100,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 38,
      },
      {
        name: "Mutton Curry Cut 500g",
        description: "Fresh goat meat, Ideal for biryani and curries, Tender pieces",
        price: 480,
        originalPrice: 520,
        image: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "500g",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 42,
      },
      {
        name: "Tiger Prawns 250g",
        description: "Fresh and large, Perfect for grilling and curries",
        price: 380,
        originalPrice: 420,
        image: "https://images.unsplash.com/photo-1565680018093-ebb6b6c07835?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "250g",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 29,
      },
      {
        name: "Chicken Eggs 6 pcs (Brown)",
        description: "Farm-fresh brown eggs, Rich in protein, Free-range",
        price: 55,
        originalPrice: 65,
        image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "6pcs",
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 64,
      },
      {
        name: "Surmai Fish 400g",
        description: "Fresh kingfish, Rich in omega-3, Perfect for frying",
        price: 350,
        originalPrice: 380,
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=400&fit=crop",
        category: "meat-seafood",
        unit: "400g",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 33,
      },

      // ==================== BABY CARE ====================
      {
        name: "Huggies Diapers Premium M 72pcs",
        description: "Ultra-soft, Superior absorbency, 12-hour dryness protection",
        price: 890,
        originalPrice: 999,
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "72pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 78,
      },
      {
        name: "Johnson's Baby Shampoo 500ml",
        description: "No More Tears formula, Gentle and mild, For delicate hair",
        price: 265,
        originalPrice: 299,
        image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "500ml",
        stock: 100,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 91,
      },
      {
        name: "Cerelac Stage 2 (6-12 months) 300g",
        description: "Wheat-based baby cereal with milk, Fortified with iron",
        price: 185,
        originalPrice: 210,
        image: "https://images.unsplash.com/photo-1519777961130-7278fee66ff6?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "300g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 65,
      },
      {
        name: "Pampers Active Baby L 92pcs",
        description: "360-degree fit, Wetness indicator, All-round protection",
        price: 950,
        originalPrice: 1099,
        image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "92pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 82,
      },
      {
        name: "Mee Mee Baby Lotion 200ml",
        description: "Aloe vera enriched, Gentle moisturizing, Hypoallergenic",
        price: 145,
        originalPrice: 165,
        image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "200ml",
        stock: 100,
        isOrganic: true,
        rating: 4.3,
        reviewCount: 34,
      },
      {
        name: "Nestle Nan Pro 1 (0-6 months) 400g",
        description: "Infant formula with DHA, HMO, and probiotics",
        price: 620,
        originalPrice: 699,
        image: "https://images.unsplash.com/photo-1590005024862-6b67679a29fb?w=400&h=400&fit=crop",
        category: "baby-care",
        unit: "400g",
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 57,
      },
      {
        name: "Chicco Baby Wipes 72pcs",
        description: "Soft and gentle, Aloe vera enriched, Hypoallergenic",
        price: 120,
        originalPrice: 140,
        image: "https://placehold.co/400x400/E3F2FD/1976D2?text=Baby+Wipes",
        category: "baby-care",
        unit: "72pcs",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 43,
      },
      {
        name: "Rattler Baby Oil 200ml",
        description: "Mineral oil with vitamin E, Gentle massage oil, Dermatologically tested",
        price: 95,
        originalPrice: 115,
        image: "https://placehold.co/400x400/F3E5F5/7B1FA2?text=Baby+Oil",
        category: "baby-care",
        unit: "200ml",
        stock: 100,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 28,
      },
    ];

    await prisma.product.createMany({ data: products });
    console.log(`Created ${products.length} products`);

    console.log("Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("========== SEED ERROR ==========");
    console.error(error);

    if (error instanceof Error) {
      console.error("Message:", error.message);
      console.error("Stack:");
      console.error(error.stack);
    }

    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
};

seedDB();